[package]
name = "qalculate"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyrun-plugin = { git = "https://github.com/anyrun-org/anyrun" }
abi_stable = "0.11.1"
serde = { version = "1.0.218", features = ["derive"] }
ron = "0.8.1"
